services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 5001:5001
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.rule=Host(`dockge.techg.ca`)
      - traefik.http.routers.dockge.entrypoints=websecure
      - traefik.http.routers.dockge.tls=true
      # - traefik.http.services.dockge.loadbalancer.server.port=5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/dockge/data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/lorne/docker:/home/lorne/docker
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/lorne/docker

networks:
  proxy:
    external: true